version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    env_file: ./.env.dev
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5434:5432
